---
format: 
  html:
    toc: true
    html-math-method: mathjax
vignette: >
  %\VignetteIndexEntry{general-demo}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---


```{r}
library(tidycensuskr)
library(dplyr)
library(sf)
options(sf_use_s2 = FALSE)
```


```{r}
# set_kosis_key("~/.kosiskey")

sgg2020 <- load_districts()
pop <- load_population(year = 2020)

# clean the population data
pop_sub <- pop %>%
  mutate(sggcd = as.character(C1)) %>%
  select(sggcd, DT, C2_NM, C3_NM) %>%
  rename(
    value = DT,
    sex = C2_NM,
    age = C3_NM
  ) %>%
  filter(sex == "계" & age == "합계") %>%
  filter(nchar(sggcd) == 5) %>%
  mutate(
    value = as.numeric(value)
  ) %>%
  mutate(sggcd = ifelse(substr(sggcd, 3, 3) %in% c("5", "6"), 
                        as.character(as.integer(sggcd) - 200), 
                        sggcd))

# join the population data with the district data
sgg2020_pop <- sgg2020 %>%
  rename(sggcd = SIGUNGU_CD) %>%
  left_join(pop_sub, by = "sggcd")


# quick plot
plot(sgg2020_pop[, "value"])
```